### ISSUE TITLE
Isn't compatible with the multiprocessing plugin

### ISSUE THREAD

**Issue by lordjabez** [leplatrem/nose-mocha-reporter#2]
I love the output of this reporter, but it appears broken when used in conjunction with the `--process` flag of nose (to do parallel testing). I get this error:

```
======================================================================
ERROR: Failure: AttributeError ('MochaReporterPlugin' object has no attribute 'stream')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/nose/case.py", line 134, in run
    self.runTest(result)
  File "/usr/local/lib/python3.7/site-packages/nose/case.py", line 152, in runTest
    test(result)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/case.py", line 663, in __call__
    return self.run(*args, **kwds)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/case.py", line 631, in run
    result.addSuccess(self)
  File "/usr/local/lib/python3.7/site-packages/nose/proxy.py", line 164, in addSuccess
    self.plugins.addSuccess(self.test)
  File "/usr/local/lib/python3.7/site-packages/nose/plugins/manager.py", line 99, in __call__
    return self.call(*arg, **kw)
  File "/usr/local/lib/python3.7/site-packages/nose/plugins/manager.py", line 167, in simple
    result = meth(*arg, **kw)
  File "/usr/local/lib/python3.7/site-packages/nose_mocha_reporter/__init__.py", line 76, in addSuccess
    self.showTestResult(u"\u2713", Colors.GREEN)
  File "/usr/local/lib/python3.7/site-packages/nose_mocha_reporter/__init__.py", line 102, in showTestResult
    self.stream.write(encode_for_stream(message))
AttributeError: 'MochaReporterPlugin' object has no attribute 'stream'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/usr/local/lib/python3.7/site-packages/nose/plugins/multiprocess.py", line 715, in __runner
    test(result)
  File "/usr/local/lib/python3.7/site-packages/nose/suite.py", line 178, in __call__
    return self.run(*arg, **kw)
  File "/usr/local/lib/python3.7/site-packages/nose/plugins/multiprocess.py", line 812, in run
    test(orig)
  File "/usr/local/lib/python3.7/site-packages/nose/suite.py", line 178, in __call__
    return self.run(*arg, **kw)
  File "/usr/local/lib/python3.7/site-packages/nose/plugins/multiprocess.py", line 812, in run
    test(orig)
  File "/usr/local/lib/python3.7/site-packages/nose/case.py", line 46, in __call__
    return self.run(*arg, **kwarg)
  File "/usr/local/lib/python3.7/site-packages/nose/case.py", line 139, in run
    result.addError(self, err)
  File "/usr/local/lib/python3.7/site-packages/nose/proxy.py", line 131, in addError
    plugins.addError(self.test, err)
  File "/usr/local/lib/python3.7/site-packages/nose/plugins/manager.py", line 99, in __call__
    return self.call(*arg, **kw)
  File "/usr/local/lib/python3.7/site-packages/nose/plugins/manager.py", line 167, in simple
    result = meth(*arg, **kw)
  File "/usr/local/lib/python3.7/site-packages/nose_mocha_reporter/__init__.py", line 79, in addError
    self.showTestResult(u"\u2717", Colors.YELLOW)
  File "/usr/local/lib/python3.7/site-packages/nose_mocha_reporter/__init__.py", line 102, in showTestResult
    self.stream.write(encode_for_stream(message))
AttributeError: 'MochaReporterPlugin' object has no attribute 'stream'

----------------------------------------------------------------------
```

**Comment by leplatrem** [comment]
Thanks for reporting!

Lately most of my projects use py.test and I don't really use it anymore... 

Are you interested to fix it? I could merge PRs or I could give you the perms on the repo / pypi
